// Code generated by ent, DO NOT EDIT.

package organizationaccounttype

import (
	"time"
)

const (
	// Label holds the string label denoting the organizationaccounttype type in the database.
	Label = "organization_account_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCategories holds the string denoting the categories edge name in mutations.
	EdgeCategories = "categories"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// Table holds the table name of the organizationaccounttype in the database.
	Table = "organization_account_types"
	// CategoriesTable is the table that holds the categories relation/edge.
	CategoriesTable = "organization_account_categories"
	// CategoriesInverseTable is the table name for the OrganizationAccountCategory entity.
	// It exists in this package in order to avoid circular dependency with the "organizationaccountcategory" package.
	CategoriesInverseTable = "organization_account_categories"
	// CategoriesColumn is the table column denoting the categories relation/edge.
	CategoriesColumn = "account_type_id"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "organization_account_types"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "organization_id"
)

// Columns holds all SQL columns for organizationaccounttype fields.
var Columns = []string{
	FieldID,
	FieldOrganizationID,
	FieldName,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
