// Code generated by ent, DO NOT EDIT.

package organizationaccount

import (
	"time"
)

const (
	// Label holds the string label denoting the organizationaccount type in the database.
	Label = "organization_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTransactions holds the string denoting the transactions edge name in mutations.
	EdgeTransactions = "transactions"
	// EdgeAccCategory holds the string denoting the acccategory edge name in mutations.
	EdgeAccCategory = "accCategory"
	// Table holds the table name of the organizationaccount in the database.
	Table = "organization_accounts"
	// TransactionsTable is the table that holds the transactions relation/edge.
	TransactionsTable = "transactions"
	// TransactionsInverseTable is the table name for the Transaction entity.
	// It exists in this package in order to avoid circular dependency with the "transaction" package.
	TransactionsInverseTable = "transactions"
	// TransactionsColumn is the table column denoting the transactions relation/edge.
	TransactionsColumn = "account_id"
	// AccCategoryTable is the table that holds the accCategory relation/edge.
	AccCategoryTable = "organization_accounts"
	// AccCategoryInverseTable is the table name for the OrganizationAccountCategory entity.
	// It exists in this package in order to avoid circular dependency with the "organizationaccountcategory" package.
	AccCategoryInverseTable = "organization_account_categories"
	// AccCategoryColumn is the table column denoting the accCategory relation/edge.
	AccCategoryColumn = "category_id"
)

// Columns holds all SQL columns for organizationaccount fields.
var Columns = []string{
	FieldID,
	FieldCategoryID,
	FieldName,
	FieldCode,
	FieldBalance,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CategoryIDValidator is a validator for the "category_id" field. It is called by the builders before save.
	CategoryIDValidator func(int) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
