// Code generated by ent, DO NOT EDIT.

package mastereventtype

import (
	"time"
)

const (
	// Label holds the string label denoting the mastereventtype type in the database.
	Label = "master_event_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldRules holds the string denoting the rules field in the database.
	FieldRules = "rules"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the mastereventtype in the database.
	Table = "master_event_types"
)

// Columns holds all SQL columns for mastereventtype fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldRules,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
