// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"outgrow/ent/masteraccount"
	"outgrow/ent/masteraccountcategory"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// MasterAccount is the model entity for the MasterAccount schema.
type MasterAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CategoryID holds the value of the "category_id" field.
	CategoryID int `json:"category_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MasterAccountQuery when eager-loading is set.
	Edges MasterAccountEdges `json:"edges"`
}

// MasterAccountEdges holds the relations/edges for other nodes in the graph.
type MasterAccountEdges struct {
	// AccCategory holds the value of the accCategory edge.
	AccCategory *MasterAccountCategory `json:"accCategory,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccCategoryOrErr returns the AccCategory value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MasterAccountEdges) AccCategoryOrErr() (*MasterAccountCategory, error) {
	if e.loadedTypes[0] {
		if e.AccCategory == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: masteraccountcategory.Label}
		}
		return e.AccCategory, nil
	}
	return nil, &NotLoadedError{edge: "accCategory"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MasterAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case masteraccount.FieldID, masteraccount.FieldCategoryID:
			values[i] = new(sql.NullInt64)
		case masteraccount.FieldName:
			values[i] = new(sql.NullString)
		case masteraccount.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type MasterAccount", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MasterAccount fields.
func (ma *MasterAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case masteraccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ma.ID = int(value.Int64)
		case masteraccount.FieldCategoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				ma.CategoryID = int(value.Int64)
			}
		case masteraccount.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ma.Name = value.String
			}
		case masteraccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ma.CreatedAt = value.Time
			}
		}
	}
	return nil
}

// QueryAccCategory queries the "accCategory" edge of the MasterAccount entity.
func (ma *MasterAccount) QueryAccCategory() *MasterAccountCategoryQuery {
	return NewMasterAccountClient(ma.config).QueryAccCategory(ma)
}

// Update returns a builder for updating this MasterAccount.
// Note that you need to call MasterAccount.Unwrap() before calling this method if this MasterAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (ma *MasterAccount) Update() *MasterAccountUpdateOne {
	return NewMasterAccountClient(ma.config).UpdateOne(ma)
}

// Unwrap unwraps the MasterAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ma *MasterAccount) Unwrap() *MasterAccount {
	_tx, ok := ma.config.driver.(*txDriver)
	if !ok {
		panic("ent: MasterAccount is not a transactional entity")
	}
	ma.config.driver = _tx.drv
	return ma
}

// String implements the fmt.Stringer.
func (ma *MasterAccount) String() string {
	var builder strings.Builder
	builder.WriteString("MasterAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ma.ID))
	builder.WriteString("category_id=")
	builder.WriteString(fmt.Sprintf("%v", ma.CategoryID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(ma.Name)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ma.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MasterAccounts is a parsable slice of MasterAccount.
type MasterAccounts []*MasterAccount
