// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"outgrow/ent/organizationaccounttype"
	"outgrow/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrganizationAccountTypeDelete is the builder for deleting a OrganizationAccountType entity.
type OrganizationAccountTypeDelete struct {
	config
	hooks    []Hook
	mutation *OrganizationAccountTypeMutation
}

// Where appends a list predicates to the OrganizationAccountTypeDelete builder.
func (oatd *OrganizationAccountTypeDelete) Where(ps ...predicate.OrganizationAccountType) *OrganizationAccountTypeDelete {
	oatd.mutation.Where(ps...)
	return oatd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (oatd *OrganizationAccountTypeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, OrganizationAccountTypeMutation](ctx, oatd.sqlExec, oatd.mutation, oatd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (oatd *OrganizationAccountTypeDelete) ExecX(ctx context.Context) int {
	n, err := oatd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (oatd *OrganizationAccountTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(organizationaccounttype.Table, sqlgraph.NewFieldSpec(organizationaccounttype.FieldID, field.TypeInt))
	if ps := oatd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, oatd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	oatd.mutation.done = true
	return affected, err
}

// OrganizationAccountTypeDeleteOne is the builder for deleting a single OrganizationAccountType entity.
type OrganizationAccountTypeDeleteOne struct {
	oatd *OrganizationAccountTypeDelete
}

// Where appends a list predicates to the OrganizationAccountTypeDelete builder.
func (oatdo *OrganizationAccountTypeDeleteOne) Where(ps ...predicate.OrganizationAccountType) *OrganizationAccountTypeDeleteOne {
	oatdo.oatd.mutation.Where(ps...)
	return oatdo
}

// Exec executes the deletion query.
func (oatdo *OrganizationAccountTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := oatdo.oatd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{organizationaccounttype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oatdo *OrganizationAccountTypeDeleteOne) ExecX(ctx context.Context) {
	if err := oatdo.Exec(ctx); err != nil {
		panic(err)
	}
}
