// Code generated by ent, DO NOT EDIT.

package ent

import (
	"outgrow/ent/event"
	"outgrow/ent/masteraccount"
	"outgrow/ent/masteraccountcategory"
	"outgrow/ent/masteraccounttype"
	"outgrow/ent/mastereventtype"
	"outgrow/ent/organization"
	"outgrow/ent/organizationaccount"
	"outgrow/ent/organizationaccountcategory"
	"outgrow/ent/organizationaccounttype"
	"outgrow/ent/organizationeventtype"
	"outgrow/ent/schema"
	"outgrow/ent/transaction"
	"outgrow/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescAmount is the schema descriptor for amount field.
	eventDescAmount := eventFields[3].Descriptor()
	// event.DefaultAmount holds the default value on creation for the amount field.
	event.DefaultAmount = eventDescAmount.Default.(float64)
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[5].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() uuid.UUID)
	masteraccountFields := schema.MasterAccount{}.Fields()
	_ = masteraccountFields
	// masteraccountDescCategoryID is the schema descriptor for category_id field.
	masteraccountDescCategoryID := masteraccountFields[0].Descriptor()
	// masteraccount.CategoryIDValidator is a validator for the "category_id" field. It is called by the builders before save.
	masteraccount.CategoryIDValidator = masteraccountDescCategoryID.Validators[0].(func(int) error)
	// masteraccountDescName is the schema descriptor for name field.
	masteraccountDescName := masteraccountFields[1].Descriptor()
	// masteraccount.NameValidator is a validator for the "name" field. It is called by the builders before save.
	masteraccount.NameValidator = masteraccountDescName.Validators[0].(func(string) error)
	// masteraccountDescCreatedAt is the schema descriptor for created_at field.
	masteraccountDescCreatedAt := masteraccountFields[2].Descriptor()
	// masteraccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	masteraccount.DefaultCreatedAt = masteraccountDescCreatedAt.Default.(func() time.Time)
	masteraccountcategoryFields := schema.MasterAccountCategory{}.Fields()
	_ = masteraccountcategoryFields
	// masteraccountcategoryDescName is the schema descriptor for name field.
	masteraccountcategoryDescName := masteraccountcategoryFields[1].Descriptor()
	// masteraccountcategory.NameValidator is a validator for the "name" field. It is called by the builders before save.
	masteraccountcategory.NameValidator = masteraccountcategoryDescName.Validators[0].(func(string) error)
	// masteraccountcategoryDescCreatedAt is the schema descriptor for created_at field.
	masteraccountcategoryDescCreatedAt := masteraccountcategoryFields[3].Descriptor()
	// masteraccountcategory.DefaultCreatedAt holds the default value on creation for the created_at field.
	masteraccountcategory.DefaultCreatedAt = masteraccountcategoryDescCreatedAt.Default.(func() time.Time)
	masteraccounttypeFields := schema.MasterAccountType{}.Fields()
	_ = masteraccounttypeFields
	// masteraccounttypeDescName is the schema descriptor for name field.
	masteraccounttypeDescName := masteraccounttypeFields[0].Descriptor()
	// masteraccounttype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	masteraccounttype.NameValidator = masteraccounttypeDescName.Validators[0].(func(string) error)
	// masteraccounttypeDescCreatedAt is the schema descriptor for created_at field.
	masteraccounttypeDescCreatedAt := masteraccounttypeFields[1].Descriptor()
	// masteraccounttype.DefaultCreatedAt holds the default value on creation for the created_at field.
	masteraccounttype.DefaultCreatedAt = masteraccounttypeDescCreatedAt.Default.(func() time.Time)
	mastereventtypeFields := schema.MasterEventType{}.Fields()
	_ = mastereventtypeFields
	// mastereventtypeDescName is the schema descriptor for name field.
	mastereventtypeDescName := mastereventtypeFields[0].Descriptor()
	// mastereventtype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	mastereventtype.NameValidator = mastereventtypeDescName.Validators[0].(func(string) error)
	// mastereventtypeDescCreatedAt is the schema descriptor for created_at field.
	mastereventtypeDescCreatedAt := mastereventtypeFields[3].Descriptor()
	// mastereventtype.DefaultCreatedAt holds the default value on creation for the created_at field.
	mastereventtype.DefaultCreatedAt = mastereventtypeDescCreatedAt.Default.(func() time.Time)
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[1].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationFields[2].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescPublicID is the schema descriptor for public_id field.
	organizationDescPublicID := organizationFields[3].Descriptor()
	// organization.PublicIDValidator is a validator for the "public_id" field. It is called by the builders before save.
	organization.PublicIDValidator = organizationDescPublicID.Validators[0].(func(string) error)
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationFields[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() uuid.UUID)
	organizationaccountFields := schema.OrganizationAccount{}.Fields()
	_ = organizationaccountFields
	// organizationaccountDescCategoryID is the schema descriptor for category_id field.
	organizationaccountDescCategoryID := organizationaccountFields[0].Descriptor()
	// organizationaccount.CategoryIDValidator is a validator for the "category_id" field. It is called by the builders before save.
	organizationaccount.CategoryIDValidator = organizationaccountDescCategoryID.Validators[0].(func(int) error)
	// organizationaccountDescName is the schema descriptor for name field.
	organizationaccountDescName := organizationaccountFields[1].Descriptor()
	// organizationaccount.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organizationaccount.NameValidator = organizationaccountDescName.Validators[0].(func(string) error)
	// organizationaccountDescBalance is the schema descriptor for balance field.
	organizationaccountDescBalance := organizationaccountFields[3].Descriptor()
	// organizationaccount.DefaultBalance holds the default value on creation for the balance field.
	organizationaccount.DefaultBalance = organizationaccountDescBalance.Default.(float64)
	// organizationaccountDescCreatedAt is the schema descriptor for created_at field.
	organizationaccountDescCreatedAt := organizationaccountFields[4].Descriptor()
	// organizationaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	organizationaccount.DefaultCreatedAt = organizationaccountDescCreatedAt.Default.(func() time.Time)
	organizationaccountcategoryFields := schema.OrganizationAccountCategory{}.Fields()
	_ = organizationaccountcategoryFields
	// organizationaccountcategoryDescName is the schema descriptor for name field.
	organizationaccountcategoryDescName := organizationaccountcategoryFields[1].Descriptor()
	// organizationaccountcategory.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organizationaccountcategory.NameValidator = organizationaccountcategoryDescName.Validators[0].(func(string) error)
	// organizationaccountcategoryDescCreatedAt is the schema descriptor for created_at field.
	organizationaccountcategoryDescCreatedAt := organizationaccountcategoryFields[3].Descriptor()
	// organizationaccountcategory.DefaultCreatedAt holds the default value on creation for the created_at field.
	organizationaccountcategory.DefaultCreatedAt = organizationaccountcategoryDescCreatedAt.Default.(func() time.Time)
	organizationaccounttypeFields := schema.OrganizationAccountType{}.Fields()
	_ = organizationaccounttypeFields
	// organizationaccounttypeDescName is the schema descriptor for name field.
	organizationaccounttypeDescName := organizationaccounttypeFields[1].Descriptor()
	// organizationaccounttype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organizationaccounttype.NameValidator = organizationaccounttypeDescName.Validators[0].(func(string) error)
	// organizationaccounttypeDescCreatedAt is the schema descriptor for created_at field.
	organizationaccounttypeDescCreatedAt := organizationaccounttypeFields[2].Descriptor()
	// organizationaccounttype.DefaultCreatedAt holds the default value on creation for the created_at field.
	organizationaccounttype.DefaultCreatedAt = organizationaccounttypeDescCreatedAt.Default.(func() time.Time)
	organizationeventtypeFields := schema.OrganizationEventType{}.Fields()
	_ = organizationeventtypeFields
	// organizationeventtypeDescName is the schema descriptor for name field.
	organizationeventtypeDescName := organizationeventtypeFields[1].Descriptor()
	// organizationeventtype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organizationeventtype.NameValidator = organizationeventtypeDescName.Validators[0].(func(string) error)
	// organizationeventtypeDescCreatedAt is the schema descriptor for created_at field.
	organizationeventtypeDescCreatedAt := organizationeventtypeFields[4].Descriptor()
	// organizationeventtype.DefaultCreatedAt holds the default value on creation for the created_at field.
	organizationeventtype.DefaultCreatedAt = organizationeventtypeDescCreatedAt.Default.(func() time.Time)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescAmount is the schema descriptor for amount field.
	transactionDescAmount := transactionFields[5].Descriptor()
	// transaction.DefaultAmount holds the default value on creation for the amount field.
	transaction.DefaultAmount = transactionDescAmount.Default.(float64)
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[7].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	// transactionDescID is the schema descriptor for id field.
	transactionDescID := transactionFields[0].Descriptor()
	// transaction.DefaultID holds the default value on creation for the id field.
	transaction.DefaultID = transactionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
