// Code generated by ent, DO NOT EDIT.

package masteraccounttype

import (
	"time"
)

const (
	// Label holds the string label denoting the masteraccounttype type in the database.
	Label = "master_account_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCategories holds the string denoting the categories edge name in mutations.
	EdgeCategories = "categories"
	// Table holds the table name of the masteraccounttype in the database.
	Table = "master_account_types"
	// CategoriesTable is the table that holds the categories relation/edge.
	CategoriesTable = "master_account_categories"
	// CategoriesInverseTable is the table name for the MasterAccountCategory entity.
	// It exists in this package in order to avoid circular dependency with the "masteraccountcategory" package.
	CategoriesInverseTable = "master_account_categories"
	// CategoriesColumn is the table column denoting the categories relation/edge.
	CategoriesColumn = "account_type_id"
)

// Columns holds all SQL columns for masteraccounttype fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
