// Code generated by ent, DO NOT EDIT.

package masteraccount

import (
	"time"
)

const (
	// Label holds the string label denoting the masteraccount type in the database.
	Label = "master_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAccCategory holds the string denoting the acccategory edge name in mutations.
	EdgeAccCategory = "accCategory"
	// Table holds the table name of the masteraccount in the database.
	Table = "master_accounts"
	// AccCategoryTable is the table that holds the accCategory relation/edge.
	AccCategoryTable = "master_accounts"
	// AccCategoryInverseTable is the table name for the MasterAccountCategory entity.
	// It exists in this package in order to avoid circular dependency with the "masteraccountcategory" package.
	AccCategoryInverseTable = "master_account_categories"
	// AccCategoryColumn is the table column denoting the accCategory relation/edge.
	AccCategoryColumn = "category_id"
)

// Columns holds all SQL columns for masteraccount fields.
var Columns = []string{
	FieldID,
	FieldCategoryID,
	FieldName,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CategoryIDValidator is a validator for the "category_id" field. It is called by the builders before save.
	CategoryIDValidator func(int) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
