// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// MasterAccount is the predicate function for masteraccount builders.
type MasterAccount func(*sql.Selector)

// MasterAccountCategory is the predicate function for masteraccountcategory builders.
type MasterAccountCategory func(*sql.Selector)

// MasterAccountType is the predicate function for masteraccounttype builders.
type MasterAccountType func(*sql.Selector)

// MasterEventType is the predicate function for mastereventtype builders.
type MasterEventType func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// OrganizationAccount is the predicate function for organizationaccount builders.
type OrganizationAccount func(*sql.Selector)

// OrganizationAccountCategory is the predicate function for organizationaccountcategory builders.
type OrganizationAccountCategory func(*sql.Selector)

// OrganizationAccountType is the predicate function for organizationaccounttype builders.
type OrganizationAccountType func(*sql.Selector)

// OrganizationEventType is the predicate function for organizationeventtype builders.
type OrganizationEventType func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
